#!/bin/sh /etc/rc.common

START=99

start() {
	lua /usr/lib/lua/luci/fiddel/server_app.lua start
}

stop() {
	lua /usr/lib/lua/luci/fiddel/server_app.lua stop
}

restart() {
	stop
	start
}

reload() {
	echo "Warning: This service does not support configuration reloading"
	echo "Performing full restart instead..."
	restart
}
